version: '{build}'
skip_tags: true
image: Visual Studio 2019
platform: x64
configuration: Release
environment:
  CFLAGS: /W4
matrix:
  fast_finish: true
install:
  - git submodule update --init --recursive
before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A x64 ..
build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln
  parallel: true
  verbosity: minimal